# Generated by Django 3.0.3 on 2020-02-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_0', models.IntegerField(blank=True, default=0, null=True)),
                ('field_1', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RandomModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_0', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('field_1', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
